### ISSUE TITLE
Token exchange not working

### ISSUE THREAD

**Issue by StueberMa** [SAP-samples/cloud-security-xsuaa-integration#200]
Apparently the token exchange functionality via the `UserTokenFlow` is not working as expected. The flow terminates with error message `Call to XSUAA was not successful: {"error":"invalid_client","error_description":"Given client ID does not match authenticated client"}`.

This is due to the fact that the underlying `RefreshTokenFlow` and `UserTokenFlow` share the same `DefaultOAuth2TokenService` and the state within the `HttpHeadersFactory` is not cleared. Therefore, the bearer token is also attached to the final execution of the `RefreshTokenFlow` which gets rejected by the UAA since in fact the client-id of the original and the refresh token deviate.

One solution could be that the methods `createWithAuthorizationBearerHeader` and `createWithoutAuthorizationHeader` of class `HttpHeadersFactory` are always executed with a fresh state or the entire state gets simply omitted from this class ...

**Comment by nenaraab** [comment]
Hi @StueberMa 
thanks for reporting.
Will fix the error [here](https://github.com/SAP-samples/cloud-security-xsuaa-integration/blob/master/token-client/src/main/java/com/sap/cloud/security/xsuaa/http/HttpHeadersFactory.java) very soon in the next days!
Best regards,
Nena

**Comment by nenaraab** [comment]
Hi, 

this should be solved in version [2.3.0](https://github.com/SAP-samples/cloud-security-xsuaa-integration/releases/tag/2.3.0).

https://search.maven.org/search?q=com.sap.cloud.security

Best regards,
Nena

**Comment by StueberMa** [comment]
@nenaraab  @hassler-d  Many thanks! It's working fine with your newly released version ... :)
